# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
maps_api_key: 'AIzaSyDDboRKTKXnsgjOOat3ZEGNVaixHN5d_PY'

development:
  secret_key_base: 4728082af67e070441d4d10d9defa5ad7327bab26126efb63315496b05dd7d249494a80d97761b7d105d916ed327b2bb757857542bcc61c84bb0b2667c1302c3
  

test:
  secret_key_base: 12fc85f1d34f0e2fb8af74f9ce0c2c1a1ce4af49299629577f0f1e4e76a16adbd9c7c60c1dcb586b660f8b166f5ded5d83b5023fda0f90770697a44e22f06e96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
